const screenStartSelector = '.screen_game_start',
  screenProcessSeelector = '.screen_game_process',
  screenEndSeelector = '.screen_game_over',
  sreenOpenedClass = 'screen_opened',
  startButtonSelector = '.screen__button_start-game',
  settingsButtonSelector = '.screen__button_settings',
  questionFormSelector = '.screen__form_questions',
  questionSelector = '.screen__question-text',
  answersContainerSelector = '.screen__answers',
  answerButtonTemplateSelector = '#answer-template',
  answerButtonSelector = '.screen__answer',
  correctAnswerClass = 'screen__answer_correct',
  incorrectAnswerClass = 'screen__answer_wrong',
  counterTextSelector = '.screen__question-number',
  nextButtonSelector = '.screen__button',
  finalTimeSelector = '.screen__final-time',
  answerResultSelector = '.screen__final-counter',
  answerIconsSelector = '.screen__answer-icons',
  correctIconSelectors = '.screen__answer-icon_correct',
  incorrectIconSelectors = '.screen__answer-icon_incorrect',
  iconsTemplateSelector = '#asnwer-icons';

export {
  screenStartSelector,
  screenProcessSeelector,
  screenEndSeelector,
  sreenOpenedClass,
  startButtonSelector,
  settingsButtonSelector,
  questionFormSelector,
  questionSelector,
  answersContainerSelector,
  answerButtonTemplateSelector,
  answerButtonSelector,
  correctAnswerClass,
  incorrectAnswerClass,
  counterTextSelector,
  nextButtonSelector,
  finalTimeSelector,
  answerResultSelector,
  answerIconsSelector,
  correctIconSelectors,
  incorrectIconSelectors,
  iconsTemplateSelector,
};
